export const courses = [
  "Information Technology",
  "Computer Science",
  "Information Systems",
  "Business Administration",
  "Accountancy",
  "Accounting Information System",
  "Hospitality Management",
  "Tourism Management",
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Electronics Engineering",
  "Architecture",
  "Nursing",
  "Pharmacy",
  "Medical Technology",
  "Psychology",
  "Criminology",
  "Education",
  "Elementary Education",
  "Secondary Education",
  "Communication",
  "Political Science",
  "English",
  "Sociology",
  "Biology",
  "Chemistry",
  "Mathematics",
  "Environmental Science",
  "Social Work",
  "Agriculture",
  "Forestry",
  "Fisheries",
  "Industrial Engineering",
  "Electronics Technology",
  "Midwifery",
  "Physical Therapy",
  "Radiologic Technology",
  "Customs Administration",
  "Maritime Transportation",
  "Marine Engineering",
];
